import { BubbleConcept } from './types';

// Pool de bolhas decorativas (modo 'decor') - exibe palavras reais em formato glassmorphic
export const DECOR_CONCEPTS: BubbleConcept[] = [
  {
    word: 'Postura',
    pillar: 'corpo',
    ref: 'postura',
    label: 'Postura',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '10%',
    size: 55,
    duration: 19,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.45,
    zIndex: 18
  },
  {
    word: 'Foco',
    pillar: 'mente',
    ref: 'foco',
    label: 'Foco',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '22%',
    size: 65,
    duration: 22,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.5,
    zIndex: 20
  },
  {
    word: 'Lazer',
    pillar: 'vida',
    ref: 'lazer',
    label: 'Lazer',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '35%',
    size: 45,
    duration: 17,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.35,
    zIndex: 14
  },
  {
    word: 'Tempo',
    pillar: 'liberdade',
    ref: 'tempo',
    label: 'Tempo',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '48%',
    size: 70,
    duration: 21,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.5,
    zIndex: 20
  },
  {
    word: 'Sonhos',
    pillar: 'proposito',
    ref: 'sonhos',
    label: 'Sonhos',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '62%',
    size: 55,
    duration: 20,
    delay: 8,
    theme: 'glass',
    maxOpacity: 0.4,
    zIndex: 18
  },
  {
    word: 'Sono',
    pillar: 'corpo',
    ref: 'sono',
    label: 'Sono',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '78%',
    size: 48,
    duration: 23,
    delay: 9,
    theme: 'glass',
    maxOpacity: 0.35,
    zIndex: 14
  },
  {
    word: 'Leitura',
    pillar: 'mente',
    ref: 'leitura',
    label: 'Leitura',
    value: 'decor',
    points: 0,
    isGameActive: false,
    left: '90%',
    size: 60,
    duration: 18,
    delay: 11,
    theme: 'glass',
    maxOpacity: 0.45,
    zIndex: 18
  }
];

/**
 * ── FASE 1: DIAGNÓSTICO DE CONHECIMENTO ──
 * Soltadas em passos separados por pilar.
 * Estilo neutro ('glass' transparente) e subida muito lenta (30s a 45s).
 * O usuário clica para marcar as coisas que fazem parte de sua rotina real atual.
 */
export const PHASE1_BUBBLES: BubbleConcept[] = [
  // ── CORPO ──
  {
    word: 'Academia',
    pillar: 'corpo',
    ref: 'academia',
    label: 'Academia',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '12%',
    size: 80,
    duration: 38,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Caminhar',
    pillar: 'corpo',
    ref: 'caminhar',
    label: 'Caminhar',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '28%',
    size: 75,
    duration: 42,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Comer Limpo',
    pillar: 'corpo',
    ref: 'comer_limpo',
    label: 'Comer Limpo',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '45%',
    size: 82,
    duration: 35,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Fast-food',
    pillar: 'corpo',
    ref: 'fast_food',
    label: 'Fast-food',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '60%',
    size: 78,
    duration: 39,
    delay: 1,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Sedentarismo',
    pillar: 'corpo',
    ref: 'sedentarismo',
    label: 'Sedentarismo',
    value: 'negative',
    points: -3,
    isGameActive: true,
    left: '75%',
    size: 80,
    duration: 44,
    delay: 3,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Insônia',
    pillar: 'corpo',
    ref: 'insonia',
    label: 'Insônia',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '90%',
    size: 74,
    duration: 36,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },

  // ── MENTE ──
  {
    word: 'Meditação',
    pillar: 'mente',
    ref: 'meditacao',
    label: 'Meditação',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '15%',
    size: 80,
    duration: 39,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Leitura',
    pillar: 'mente',
    ref: 'leitura',
    label: 'Leitura',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '32%',
    size: 76,
    duration: 41,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Terapia',
    pillar: 'mente',
    ref: 'terapia',
    label: 'Terapia',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '52%',
    size: 82,
    duration: 37,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Telas até Tarde',
    pillar: 'mente',
    ref: 'telas_tarde',
    label: 'Telas até Tarde',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '68%',
    size: 84,
    duration: 43,
    delay: 1,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Ansiedade',
    pillar: 'mente',
    ref: 'ansiedade',
    label: 'Ansiedade',
    value: 'negative',
    points: -3,
    isGameActive: true,
    left: '82%',
    size: 78,
    duration: 35,
    delay: 3,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Redes Sociais',
    pillar: 'mente',
    ref: 'redes_sociais',
    label: 'Redes Sociais',
    value: 'negative',
    points: -1,
    isGameActive: true,
    left: '92%',
    size: 74,
    duration: 40,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },

  // ── VIDA ──
  {
    word: 'Família',
    pillar: 'vida',
    ref: 'familia',
    label: 'Família',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '10%',
    size: 80,
    duration: 37,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Amigos',
    pillar: 'vida',
    ref: 'amigos',
    label: 'Amigos',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '26%',
    size: 76,
    duration: 42,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Pesca/Hobbies',
    pillar: 'vida',
    ref: 'pesca_hobbies',
    label: 'Pesca/Hobbies',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '42%',
    size: 82,
    duration: 38,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Trabalho Excessivo',
    pillar: 'vida',
    ref: 'trabalho_excessivo',
    label: 'Trabalho Excessivo',
    value: 'negative',
    points: -3,
    isGameActive: true,
    left: '58%',
    size: 84,
    duration: 40,
    delay: 1,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Isolamento',
    pillar: 'vida',
    ref: 'isolamento',
    label: 'Isolamento',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '74%',
    size: 78,
    duration: 44,
    delay: 3,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Netflix/Telas',
    pillar: 'vida',
    ref: 'netflix_telas',
    label: 'Netflix/Telas',
    value: 'positive',
    points: 1,
    isGameActive: true,
    left: '88%',
    size: 74,
    duration: 35,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },

  // ── LIBERDADE ──
  {
    word: 'Investir',
    pillar: 'liberdade',
    ref: 'investir',
    label: 'Investir',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '14%',
    size: 80,
    duration: 39,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Poupar',
    pillar: 'liberdade',
    ref: 'poupar',
    label: 'Poupar',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '30%',
    size: 76,
    duration: 43,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Orçamento',
    pillar: 'liberdade',
    ref: 'orcamento',
    label: 'Orçamento',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '48%',
    size: 82,
    duration: 36,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Dívidas',
    pillar: 'liberdade',
    ref: 'dividas',
    label: 'Dívidas',
    value: 'negative',
    points: -3,
    isGameActive: true,
    left: '64%',
    size: 84,
    duration: 41,
    delay: 1,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Consumismo',
    pillar: 'liberdade',
    ref: 'consumismo',
    label: 'Consumismo',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '78%',
    size: 78,
    duration: 45,
    delay: 3,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Renda Extra',
    pillar: 'liberdade',
    ref: 'renda_extra',
    label: 'Renda Extra',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '90%',
    size: 74,
    duration: 37,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },

  // ── PROPÓSITO ──
  {
    word: 'Carreira Significado',
    pillar: 'proposito',
    ref: 'carreira_significado',
    label: 'Carreira Significado',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '12%',
    size: 80,
    duration: 38,
    delay: 0,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Metas Claras',
    pillar: 'proposito',
    ref: 'metas_claras',
    label: 'Metas Claras',
    value: 'positive',
    points: 3,
    isGameActive: true,
    left: '28%',
    size: 76,
    duration: 42,
    delay: 2,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Aprender/Evoluir',
    pillar: 'proposito',
    ref: 'aprender_evoluir',
    label: 'Aprender/Evoluir',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '46%',
    size: 82,
    duration: 35,
    delay: 4,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Procrastinação',
    pillar: 'proposito',
    ref: 'procrastinacao',
    label: 'Procrastinação',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '62%',
    size: 84,
    duration: 40,
    delay: 1,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Rotina Vazia',
    pillar: 'proposito',
    ref: 'rotina_vazia',
    label: 'Rotina Vazia',
    value: 'negative',
    points: -3,
    isGameActive: true,
    left: '78%',
    size: 78,
    duration: 44,
    delay: 3,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  },
  {
    word: 'Trabalho Automático',
    pillar: 'proposito',
    ref: 'trabalho_automatico',
    label: 'Trabalho Automático',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '92%',
    size: 74,
    duration: 36,
    delay: 5,
    theme: 'glass',
    maxOpacity: 0.8,
    zIndex: 20
  }
];

/**
 * ── FASE 2: DESAFIO DE EQUILÍBRIO MULTIDIMENSIONAL ──
 * Soltadas simultaneamente com cores vivas e velocidades padrão.
 * Cada bolha afeta múltiplos pilares através do objeto 'impacts'.
 */
export const PHASE2_BUBBLES: BubbleConcept[] = [
  {
    word: 'Fast-food',
    pillar: 'corpo',
    ref: 'fast_food_2',
    label: 'Fast-food',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '12%',
    size: 78,
    duration: 25,
    delay: 0,
    theme: 'rose',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: -3, mente: 0, vida: 2, liberdade: -1, proposito: -1 }
  },
  {
    word: 'Hora Extra',
    pillar: 'liberdade',
    ref: 'hora_extra',
    label: 'Hora Extra',
    value: 'positive',
    points: 1,
    isGameActive: true,
    left: '28%',
    size: 76,
    duration: 22,
    delay: 2,
    theme: 'gold',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: -2, mente: -2, vida: -2, liberdade: 3, proposito: 1 }
  },
  {
    word: 'Academia',
    pillar: 'corpo',
    ref: 'academia_2',
    label: 'Academia',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '44%',
    size: 80,
    duration: 24,
    delay: 4,
    theme: 'emerald',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 3, mente: 1, vida: -1, liberdade: -1, proposito: 0 }
  },
  {
    word: 'Viagem Amigos',
    pillar: 'vida',
    ref: 'viagem_amigos',
    label: 'Viagem Amigos',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '60%',
    size: 82,
    duration: 21,
    delay: 1,
    theme: 'blue',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 1, mente: 2, vida: 3, liberdade: -2, proposito: 0 }
  },
  {
    word: 'Estudos',
    pillar: 'proposito',
    ref: 'estudos',
    label: 'Estudos/Curso',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '76%',
    size: 78,
    duration: 23,
    delay: 3,
    theme: 'violet',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 0, mente: 2, vida: -1, liberdade: -1, proposito: 3 }
  },
  {
    word: 'Netflix',
    pillar: 'vida',
    ref: 'netflix',
    label: 'Maratonar Netflix',
    value: 'negative',
    points: -1,
    isGameActive: true,
    left: '90%',
    size: 74,
    duration: 26,
    delay: 5,
    theme: 'rose',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: -1, mente: -1, vida: 2, liberdade: 0, proposito: -2 }
  },
  {
    word: 'Meditação',
    pillar: 'mente',
    ref: 'meditacao_2',
    label: 'Meditação',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '18%',
    size: 76,
    duration: 25,
    delay: 7,
    theme: 'emerald',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 1, mente: 3, vida: 0, liberdade: 0, proposito: 1 }
  },
  {
    word: 'Consumismo',
    pillar: 'liberdade',
    ref: 'consumismo_2',
    label: 'Compras por Impulso',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '34%',
    size: 80,
    duration: 22,
    delay: 8,
    theme: 'rose',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 0, mente: -1, vida: 1, liberdade: -3, proposito: -1 }
  },
  {
    word: 'Dormir Cedo',
    pillar: 'corpo',
    ref: 'dormir_cedo',
    label: 'Dormir Cedo',
    value: 'positive',
    points: 2,
    isGameActive: true,
    left: '52%',
    size: 74,
    duration: 23,
    delay: 10,
    theme: 'emerald',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: 3, mente: 2, vida: -1, liberdade: 0, proposito: 0 }
  },
  {
    word: 'Procrastinação',
    pillar: 'proposito',
    ref: 'procrastinacao_2',
    label: 'Procrastinação',
    value: 'negative',
    points: -2,
    isGameActive: true,
    left: '70%',
    size: 78,
    duration: 26,
    delay: 12,
    theme: 'rose',
    maxOpacity: 0.8,
    zIndex: 20,
    impacts: { corpo: -1, mente: -2, vida: 1, liberdade: 0, proposito: -3 }
  }
];

// Mantido por compatibilidade legada apenas para evitar quebras em arquivos não editados
export const BASE_CONCEPTS = PHASE2_BUBBLES;
